/**
 * parseQrScan — parses a raw QR/barcode scan value into a lookup key.
 *
 * The QR codes generated by RecordList (showQrColumn) encode a full URL:
 *   https://...domain.../production/{orderId}
 *
 * Barcode scanners also commonly output plain codes like "ORD-001" or just the
 * MongoDB ObjectId directly. This utility normalises both cases.
 *
 * Returns:
 *   { type: "id",   value: "507f1f77bcf86cd799439011" }  — extract from URL or plain ObjectId
 *   { type: "code", value: "ORD-001" }                   — short code, use as search param
 */

export interface ParsedQr {
    type: "id" | "code";
    value: string;
}

/** 24-hex MongoDB ObjectId pattern */
const OBJECT_ID_RE = /^[0-9a-f]{24}$/i;

/**
 * Try to extract an ObjectId from a URL path like:
 *   /production/507f1f77bcf86cd799439011
 *   /orders/507f1f77bcf86cd799439011
 * Returns the id string or null.
 */
function extractIdFromUrl(raw: string): string | null {
    try {
        const url = new URL(raw);
        // Look for a 24-hex segment anywhere in the pathname
        const parts = url.pathname.split("/").filter(Boolean);
        for (const part of parts) {
            if (OBJECT_ID_RE.test(part)) return part;
        }
    } catch {
        // Not a valid URL — handled below
    }
    return null;
}

export function parseQrScan(raw: string): ParsedQr {
    const trimmed = raw.trim();

    // 1. Full URL — extract ObjectId from path
    if (trimmed.startsWith("http://") || trimmed.startsWith("https://")) {
        const id = extractIdFromUrl(trimmed);
        if (id) return { type: "id", value: id };
        // URL but no ObjectId found — return the whole trimmed string as code
        return { type: "code", value: trimmed };
    }

    // 2. Plain ObjectId (24 hex chars)
    if (OBJECT_ID_RE.test(trimmed)) {
        return { type: "id", value: trimmed };
    }

    // 3. Short code or custom identifier (e.g. "ORD-001", "C001")
    return { type: "code", value: trimmed.toUpperCase() };
}
